### ISSUE TITLE
Create release

### ISSUE THREAD

**Issue by lbartoletti** [lumina-desktop/lumina-calculator#1]
Same as https://github.com/lumina-desktop/lumina-pdf/issues/4

Please, can you versioning and create release for this tool?
I used tagname for the FreeBSD port when I updated Lumina to 1.5.0. But the tools isn't clearly tagged as 1.5.0.

Thank you

**Comment by beanpole135** [comment]
Done! A new "v1.5.0" tag is now available for packaging systems to use.
